# Generated by Django 5.1.6 on 2025-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours'), ('completed', 'Terminé'), ('failed', 'Abandonné')], default='pending', max_length=10),
        ),
    ]
