# Generated by Django 5.1.6 on 2025-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_updated_at_alter_challenge_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du défi'),
        ),
    ]
