# Generated by Django 5.1.6 on 2025-03-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
